TrajectoryPlannerROS:
  max_vel_x: 1.0
  min_vel_x: 1.0
  escape_vel: -1.0
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 1.0

  acc_lim_theta: 1
  acc_lim_x: 1
  acc_lim_y: 0

  holonomic_robot: false
  yaw_goal_tolerance: 1.5708
  xy_goal_tolerance: 1
  goal_distance_bias: 0.2
  path_distance_bias: 0.1
  sim_time: 1.5
  heading_lookahead: 0.325
  oscillation_reset_dist: 0.05

  vx_samples: 6
  vtheta_samples: 20

  dwa: true
